name: t1-kafka-actuator
version: '3.9'
services:
  t1-kafka-consumer:
    image: t1-kafka-consumer
    container_name: t1-kafka-consumer
    build:
      context: .
      dockerfile: consumerDockerfile
    restart: no
    environment:
      APP_LOGGING_LEVEL: INFO
    depends_on:
      - t1-kafka
    ports:
      - "8082:8082"
    networks:
      - t1-kafka-actuator

  t1-kafka-producer:
    image: t1-kafka-producer
    container_name: t1-kafka-producer
    build:
      context: .
      dockerfile: producerDockerfile
    restart: no
    environment:
      APP_LOGGING_LEVEL: OFF
    depends_on:
      - t1-kafka
    ports:
      - "8081:8081"
    networks:
      - t1-kafka-actuator

#TODO
  t1-kafka:
    container_name: t1-kafka
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - t1-kafka-actuator

networks:
  t1-kafka-actuator:
    driver: bridge
