version: '2'
services:
  t1-zookeeper-standalone:
    container_name: t1-zookeeper-standalone
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "39181:2181"
    networks:
      - t1-kafka-net

  t1-kafka-standalone:
    container_name: t1-kafka-standalone
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - t1-zookeeper-standalone
    ports:
      - "39092:39093"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_PROTOCOL_NAME: INTERNAL
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 't1-zookeeper-standalone:2181'
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:39093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://t1-kafka-standalone:9092,OUTSIDE://127.0.0.1:39092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - t1-kafka-net

networks:
  t1-kafka-net:
    driver: bridge
